'use client';
import {useEffect,useState} from 'react'; import type {Item,AdminUser,Creator,ActionLog} from '@/lib/types';
type Kind=Item['kind']; const labels:Record<Kind,string>={news:'Новости',district:'Районы',tab:'Вкладки',link:'Ссылки'};
const msk=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()).replace(' ','T');
const empty=(kind:Kind)=>({kind,title:'',body:'',image_url:'',video_url:'',video_title:'',video_description:'',video_preview:'',published_at:kind==='news'?msk():'',url:'',extra_links:[],sort_order:0,status:'published'});
export default function AdminClient({initial}:{initial:Item[]}){const [items,setItems]=useState(initial),[section,setSection]=useState('news'),[form,setForm]=useState<any>(empty('news')),[editId,setEditId]=useState<number|null>(null),[msg,setMsg]=useState(''),[data,setData]=useState<{admins:AdminUser[],creators:Creator[],logs:ActionLog[],version:string}>({admins:[],creators:[],logs:[],version:'1.0.0'}),[creator,setCreator]=useState<any>({nickname:'',body:'',avatar_url:'',url:'',district_id:''}),[admin,setAdmin]=useState<any>({username:'',password:'',display_name:''}),[version,setVersion]=useState('1.0.0'),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[editingAdmin,setEditingAdmin]=useState<number|null>(null);
 const load=async()=>{const [a,b]=await Promise.all([fetch('/api/content',{cache:'no-store'}),fetch('/api/admin/data',{cache:'no-store'})]);if(a.ok)setItems(await a.json());if(b.ok){const x=await b.json();setData(x);setVersion(x.version)}};useEffect(()=>{const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const kind=(section as Kind); const isKind=['news','district','tab','link'].includes(section);
 const start=(k:Kind)=>{setSection(k);setForm(empty(k));setEditId(null);setMsg('')}; const edit=(x:Item)=>{setSection(x.kind);setEditId(x.id);setForm({...x,extra_links:Array.isArray(x.extra_links)?x.extra_links:[]})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setPending(true);setMsg('');try{const r=await fetch('/api/content',{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editId?{...form,id:editId}:form)});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка сохранения');return}setMsg('Сохранено');setEditId(null);setForm(empty(form.kind));load()}catch(err:any){setMsg(err?.message||'Ошибка сети')}finally{setBusy(false);setPending(false)}};
 const upload=async(file:File,key:string)=>{setMsg('Загрузка файла…');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd});const j=await r.json();if(!r.ok){setMsg(j.error||'Ошибка загрузки');return}setForm((f:any)=>({...f,[key]:j.url}));setMsg('Файл загружен')};
 const api=async(type:string,payload:any)=>{const r=await fetch('/api/admin/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...payload})});const j=await r.json();setMsg(r.ok?'Сохранено':j.error||'Ошибка');if(r.ok)load()};
 return <main className="admin"><aside className="admin-sidebar"><h2>MegaMine CMS</h2>{(['news','district','tab','link','creators','admins','logs','version'] as string[]).map(x=><button key={x} className={section===x?'active':''} onClick={()=>isKind?start(x as Kind):setSection(x)}>{isKind?labels[x as Kind]:(({creators:'Создатели',admins:'Администраторы',logs:'Журнал действий',version:'Версия'} as Record<string,string>)[x])}</button>)}<a href="/">На сайт ↗</a></aside><section className="admin-main"><h1>{isKind?labels[kind]:(({creators:'Создатели',admins:'Администраторы',logs:'Последние действия',version:'Версия сайта'} as Record<string,string>)[section])}</h1>{msg&&<div className="notice">{msg}</div>}
 {isKind&&<><button className="primary" onClick={()=>start(kind)}>＋ Добавить</button><div className="admin-list">{items.filter(x=>x.kind===kind).map(x=><div className="admin-row" key={x.id}><b>{x.title}</b><small>{x.status||'published'} {x.published_at&&new Date(x.published_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})}</small><button onClick={()=>edit(x)}>Изменить</button><button onClick={async()=>{if(confirm('Удалить?')){await fetch('/api/content',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id})});load()}}}>Удалить</button></div>)}</div><form onSubmit={save} className="admin-form"><h2>{editId?'Редактирование':'Новый элемент'}</h2><label>Название<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Описание<textarea rows={5} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label>{kind==='news'&&<><label>Публикация по МСК<input type="datetime-local" step="1" value={form.published_at} onChange={e=>setForm({...form,published_at:e.target.value})}/><small>Будущая дата автоматически создаёт отложенную публикацию.</small></label><label>Статус<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="published">Опубликовать</option><option value="pending">На одобрении</option><option value="rejected">Отклонено</option></select></label></>}<label>Фото / превью<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'image_url')}/><input placeholder="URL" value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})}/></label>{kind==='news'&&<><label>Видео файл<input type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'video_url')}/></label><label>Название видео<input value={form.video_title||''} onChange={e=>setForm({...form,video_title:e.target.value})}/></label><label>Описание видео<textarea value={form.video_description||''} onChange={e=>setForm({...form,video_description:e.target.value})}/></label><label>Превью видео<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'video_preview')}/></label></>}{kind==='link'&&<label>Куда перейти<input type="url" value={form.url||''} onChange={e=>setForm({...form,url:e.target.value})}/></label>}{kind==='tab'&&<label>Ссылка<input type="url" value={form.url||''} onChange={e=>setForm({...form,url:e.target.value})}/></label>}<button className="primary" disabled={busy}>{(busy||pending)?'Сохранение…':editId?'Сохранить':'Добавить'}</button></form></>}
 {section==='creators'&&<><form className="admin-form" onSubmit={e=>{e.preventDefault();api('creator',creator)}}><label>Ник<input value={creator.nickname} onChange={e=>setCreator({...creator,nickname:e.target.value})}/></label><label>Описание<textarea value={creator.body} onChange={e=>setCreator({...creator,body:e.target.value})}/></label><label>Аватар<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'avatar_url')}/></label><label>Ссылка<input value={creator.url} onChange={e=>setCreator({...creator,url:e.target.value})}/></label><label>Привязанный район<select value={creator.district_id} onChange={e=>setCreator({...creator,district_id:e.target.value})}><option value="">Не выбран</option>{items.filter(x=>x.kind==='district').map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><button className="primary">Добавить создателя</button></form>{data.creators.map(c=><div className="admin-row" key={c.id}><b>{c.nickname}</b><span>{c.body}</span></div>)}</>}
 {section==='admins'&&<><p>Владелец: <b>логин 0</b>. При смене пароля администратора все сессии именно этого администратора автоматически завершаются.</p><form className="admin-form" onSubmit={async e=>{e.preventDefault();if(editingAdmin){const r=await fetch('/api/admin/data',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'admin',id:editingAdmin,...admin})});const j=await r.json().catch(()=>({}));setMsg(r.ok?'Администратор обновлён':j.error||'Ошибка');if(r.ok){setEditingAdmin(null);setAdmin({username:'',password:'',display_name:''});load()}}else await api('admin',admin)}}><label>Логин<input value={admin.username} onChange={e=>setAdmin({...admin,username:e.target.value})}/></label><label>{editingAdmin?'Новый пароль (оставь пустым, чтобы не менять)':'Пароль'}<input type="password" value={admin.password} onChange={e=>setAdmin({...admin,password:e.target.value})}/></label><label>Имя<input value={admin.display_name} onChange={e=>setAdmin({...admin,display_name:e.target.value})}/></label><button className="primary">{editingAdmin?'Сохранить изменения':'Добавить администратора'}</button>{editingAdmin&&<button type="button" onClick={()=>{setEditingAdmin(null);setAdmin({username:'',password:'',display_name:''})}}>Отмена</button>}</form>{data.admins.map(a=><div className="admin-row" key={a.id}><b>{a.username}</b><span>{a.display_name}</span><button onClick={()=>{setEditingAdmin(a.id);setAdmin({username:a.username,password:'',display_name:a.display_name})}}>Изменить</button><button onClick={async()=>{if(!confirm('Удалить логин? Его сессии также перестанут работать.'))return;const r=await fetch('/api/admin/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'admin',id:a.id})});const j=await r.json().catch(()=>({}));setMsg(r.ok?'Удалено':j.error||'Ошибка');load()}}>Удалить</button></div>)}</>}
 {section==='logs'&&<div className="admin-list">{data.logs.map(l=><div className="admin-row" key={l.id}><b>{l.action}</b><span>{l.username} — {l.details}</span><small>{new Date(l.created_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} МСК</small></div>)}</div>}
 {section==='version'&&<form className="admin-form" onSubmit={e=>{e.preventDefault();api('version',{version})}}><label>Версия<input value={version} onChange={e=>setVersion(e.target.value)}/></label><button className="primary">Сохранить версию</button></form>}
 </section></main>}
