'use client';
import {useEffect,useMemo,useState} from 'react';
import type {Item,ActionLog} from '@/lib/types';
type Kind=Item['kind'];
type Section=Kind|'broadcasts'|'settings'|'logs';
const labels:Record<Kind,string>={news:'Новости',district:'Районы',tab:'Вкладки',link:'Ссылки',video:'Видео'};
const sections:{id:Section;label:string}[]=[
 {id:'news',label:'📰 Новости'},{id:'district',label:'🏘️ Районы'},{id:'tab',label:'📑 Вкладки'},
 {id:'link',label:'🔗 Ссылки'},{id:'video',label:'🎥 Видео'},{id:'broadcasts',label:'📣 Рассылки'},
 {id:'settings',label:'⚙️ Сайт и дата'},{id:'logs',label:'📋 Журнал'}
];
const megaLocal=()=>new Date(Date.now()+4*3600e3).toISOString().slice(0,16);
const toMegaInput=(value:any)=>{if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Date(d.getTime()+4*3600e3).toISOString().slice(0,16)};
const empty=(kind:Kind):any=>({kind,title:'',body:'',image_url:'',video_url:'',video_title:'',video_description:'',video_preview:'',published_at:(kind==='news'||kind==='video')?megaLocal():'',url:'',extra_links:[],sort_order:0,minecraft_version:''});
export default function AdminClient({initial}:{initial:Item[]}){
 const [items,setItems]=useState(initial),[section,setSection]=useState<Section>('news'),[form,setForm]=useState<any>(empty('news')),[editId,setEditId]=useState<number|null>(null);
 const [data,setData]=useState<any>({logs:[],settings:{},broadcasts:[]}),[settings,setSettings]=useState<any>({app_version:'',app_description:'',megamine_date:'',new_password:''});
 const [broadcast,setBroadcast]=useState<any>({title:'',body:'',active:true}),[editingBroadcast,setEditingBroadcast]=useState<number|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [a,b]=await Promise.all([fetch('/api/content',{cache:'no-store'}),fetch('/api/admin/data',{cache:'no-store'})]);if(a.ok)setItems(await a.json());if(b.ok){const x=await b.json();setData(x);setSettings((s:any)=>({...s,app_version:x.settings?.app_version||'',app_description:x.settings?.app_description||'',megamine_date:x.settings?.megamine_date||''}))}}catch{}};
 useEffect(()=>{load();const t=setInterval(load,2500);return()=>clearInterval(t)},[]);
 const isKind=(s:Section):s is Kind=>['news','district','tab','link','video'].includes(s);
 const open=(s:Section)=>{setSection(s);setMsg('');if(isKind(s)){setEditId(null);setForm(empty(s))}};
 const upload=async(file:File)=>{setBusy(true);setMsg('Загрузка файла…');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Ошибка загрузки');if(!j.url)throw Error('Сервер не вернул ссылку на файл');setMsg('Файл загружен и привязан к материалу. Теперь можно сохранять изменения.');return String(j.url)}catch(e:any){setMsg(e.message||'Ошибка загрузки');return null}finally{setBusy(false)}};
 const saveContent=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch('/api/content',{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editId?{...form,id:editId}:form)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Ошибка');setMsg(editId?'Изменения сохранены':'Материал добавлен');setEditId(null);setForm(empty(form.kind));await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const edit=(x:Item)=>{setSection(x.kind);setEditId(x.id);setForm({...empty(x.kind),...x,published_at:toMegaInput(x.published_at),extra_links:Array.isArray(x.extra_links)?x.extra_links:[]})};
 const remove=async(id:number)=>{if(!confirm('Удалить этот элемент?'))return;const r=await fetch('/api/content',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok){const j=await r.json().catch(()=>({}));setMsg(j.error||'Не удалось удалить')}await load()};
 const saveBroadcast=async(e:React.FormEvent)=>{e.preventDefault();const method=editingBroadcast?'PUT':'POST';const r=await fetch('/api/admin/data',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(editingBroadcast?{type:'broadcast',id:editingBroadcast,...broadcast}:{type:'broadcast',...broadcast})}),j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка');return}setMsg('Рассылка сохранена');setEditingBroadcast(null);setBroadcast({title:'',body:'',active:true});load()};
 const saveSettings=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'settings',...settings})}),j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка');return}setMsg('Настройки сохранены. При смене пароля текущая сессия завершится.');if(settings.new_password){setTimeout(()=>location.href='/admin/login',300)}setSettings({...settings,new_password:''});load()};
 const contentTitle=isKind(section)?labels[section]:({broadcasts:'Рассылки',settings:'Сайт и дата',logs:'Журнал действий'} as Record<string,string>)[section];
 return <main className="admin"><aside className="admin-sidebar"><h2>MEGAMINE CMS</h2>{sections.map(s=><button key={s.id} className={section===s.id?'active':''} onClick={()=>open(s.id)}>{s.label}</button>)}<div className="side-divider"/><a href="/">← На сайт</a><button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}}>Выйти</button></aside><section className="admin-main"><header className="admin-page-head"><span className="eyebrow">ПОЛНЫЙ ДОСТУП • АВТООБНОВЛЕНИЕ • MEGAMINE UTC+4</span><h1>{contentTitle}</h1></header>{msg&&<div className="notice">{msg}</div>}
 {isKind(section)&&<div className="admin-split"><div className="admin-list panel"><div className="panel-head"><h2>{labels[section]}</h2><button className="primary" onClick={()=>{setEditId(null);setForm(empty(section))}}>＋ Добавить</button></div>{items.filter(x=>x.kind===section).map(x=><article className="admin-row" key={x.id}><div><b>{x.title}</b><small>{x.minecraft_version?'• Bedrock '+x.minecraft_version:''}{x.published_at?' • '+toMegaInput(x.published_at).replace('T',' '):''}</small></div><div className="row-actions"><button onClick={()=>edit(x)}>Изменить</button><button className="danger" onClick={()=>remove(x.id)}>Удалить</button></div></article>)}{!items.some(x=>x.kind===section)&&<p className="empty-mini">Пока ничего нет.</p>}</div><form className="admin-form panel" onSubmit={saveContent}><h2>{editId?'Редактирование':'Новый элемент'}</h2><label>Название<input required value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Описание<textarea rows={5} value={form.body||''} onChange={e=>setForm({...form,body:e.target.value})}/></label>
 {section==='link'&&<label>Основная ссылка (URL)<input required type="url" placeholder="https://..." value={form.url||''} onChange={e=>setForm({...form,url:e.target.value})}/></label>}
 {(section==='news'||section==='district'||section==='tab'||section==='link')&&<ExtraLinks value={Array.isArray(form.extra_links)?form.extra_links:[]} onChange={(extra_links:any)=>setForm({...form,extra_links})}/>} 
 {section==='district'&&<label>Версия Minecraft Bedrock района<input placeholder="например 1.21.100" value={form.minecraft_version||''} onChange={e=>setForm({...form,minecraft_version:e.target.value})}/></label>}
 {(section==='news'||section==='video')&&<label>Дата и время MegaMine (UTC+4)<input type="datetime-local" value={form.published_at||''} onChange={e=>setForm({...form,published_at:e.target.value})}/><small>Если указано будущее время, материал появится автоматически в указанное время.</small></label>}
 <label>{section==='video'?'Изображение карточки':'Изображение из устройства'}<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setForm((prev:any)=>({...prev,image_url:u}))}e.currentTarget.value=''}}/>{form.image_url&&<MediaState label="✓ Фото добавлено" url={form.image_url}/>}</label>
 {section==='video'&&<><label>Видеофайл<input required={!form.video_url} type="file" accept="video/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setForm((prev:any)=>({...prev,video_url:u}))}e.currentTarget.value=''}}/>{form.video_url&&<MediaState label="✓ Видео добавлено" url={form.video_url} video/>}</label><label>Название видео<input value={form.video_title||''} onChange={e=>setForm({...form,video_title:e.target.value})}/></label><label>Описание видео<textarea rows={3} value={form.video_description||''} onChange={e=>setForm({...form,video_description:e.target.value})}/></label><label>Превью видео из устройства<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setForm((prev:any)=>({...prev,video_preview:u}))}e.currentTarget.value=''}}/>{form.video_preview&&<MediaState label="✓ Превью добавлено" url={form.video_preview}/>}</label></>}
 <button className="primary" disabled={busy}>{busy?'Сохранение…':editId?'Сохранить':'Добавить'}</button></form></div>}
 {section==='broadcasts'&&<div className="admin-split"><div className="panel admin-list"><p className="muted">Активные рассылки отображаются на главной странице и обновляются автоматически.</p>{(data.broadcasts||[]).map((b:any)=><article className="admin-row" key={b.id}><div><b>{b.title}</b><small>{b.active?'Активна':'Выключена'} • {b.body}</small></div><div className="row-actions"><button onClick={()=>{setEditingBroadcast(b.id);setBroadcast({title:b.title,body:b.body,active:b.active})}}>Изменить</button><button className="danger" onClick={async()=>{if(confirm('Удалить рассылку?')){await fetch('/api/admin/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'broadcast',id:b.id})});load()}}}>Удалить</button></div></article>)}</div><form className="admin-form panel" onSubmit={saveBroadcast}><h2>{editingBroadcast?'Изменить рассылку':'Новая рассылка'}</h2><label>Заголовок<input required value={broadcast.title} onChange={e=>setBroadcast({...broadcast,title:e.target.value})}/></label><label>Текст<textarea rows={6} value={broadcast.body} onChange={e=>setBroadcast({...broadcast,body:e.target.value})}/></label><label className="inline-check"><input type="checkbox" checked={broadcast.active} onChange={e=>setBroadcast({...broadcast,active:e.target.checked})}/> Показывать на сайте</label><button className="primary">Сохранить</button></form></div>}
 {section==='settings'&&<form className="admin-form panel version-form" onSubmit={saveSettings}><h2>Версия сайта, дата и пароль</h2><label>Версия сайта<input required placeholder="например 8.9" value={settings.app_version} onChange={e=>setSettings({...settings,app_version:e.target.value})}/></label><label>Описание обновления<textarea rows={5} value={settings.app_description} onChange={e=>setSettings({...settings,app_description:e.target.value})}/></label><label>Дата MegaMine на главном экране<input type="date" value={settings.megamine_date} onChange={e=>setSettings({...settings,megamine_date:e.target.value})}/><small>Меняется только дата. Время продолжает идти реально по MegaMine UTC+4.</small></label><label>Новый пароль админ-панели (необязательно)<input type="password" minLength={4} placeholder="Оставьте пустым, чтобы не менять" value={settings.new_password||''} onChange={e=>setSettings({...settings,new_password:e.target.value})}/><small>После смены пароля все текущие сессии завершаются.</small></label><button className="primary">Сохранить настройки</button></form>}
 {section==='logs'&&<div className="panel admin-list"><p className="muted">Последние 10 действий.</p>{(data.logs||[]).map((l:ActionLog)=><article className="admin-row" key={l.id}><div><b>{l.action}</b><small>{l.username} — {l.details}</small></div><time>{new Date(new Date(l.created_at).getTime()+4*3600e3).toISOString().replace('T',' ').slice(0,19)}</time></article>)}{!(data.logs||[]).length&&<p className="empty-mini">Действий пока нет.</p>}</div>}
 </section></main>
}
function MediaState({label,url,video=false}:{label:string;url:string;video?:boolean}){return <div className="media-state"><b>{label}</b><a href={url} target="_blank" rel="noreferrer">Открыть файл ↗</a>{!video&&<img src={url} alt="Загружено"/>}</div>}
function ExtraLinks({value,onChange}:{value:any[];onChange:(v:any[])=>void}){const [busy,setBusy]=useState<number|null>(null);const uploadLinkImage=async(file:File,i:number)=>{setBusy(i);try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok||!j.url)throw Error(j.error||'Не удалось загрузить изображение');const n=[...value];n[i]={...n[i],image_url:String(j.url)};onChange(n)}catch(e:any){alert(e.message||'Ошибка загрузки')}finally{setBusy(null)}};return <div className="extra-links"><b>Отдельные ссылки этого материала</b><small>Для каждой новости, района, вкладки или общей ссылки можно создать собственные карточки-ссылки с названием, описанием, фотографией и URL.</small>{value.map((l:any,i:number)=><div className="extra-link-card" key={i}><div className="extra-link-row"><input placeholder="Название ссылки" value={l.title||''} onChange={e=>{const n=[...value];n[i]={...n[i],title:e.target.value};onChange(n)}}/><input type="url" placeholder="https://..." value={l.url||''} onChange={e=>{const n=[...value];n[i]={...n[i],url:e.target.value};onChange(n)}}/></div><textarea rows={2} placeholder="Описание ссылки" value={l.description||''} onChange={e=>{const n=[...value];n[i]={...n[i],description:e.target.value};onChange(n)}}/><label>Фото ссылки<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)uploadLinkImage(f,i);e.currentTarget.value=''}}/>{busy===i&&<small>Загрузка…</small>}{l.image_url&&<MediaState label="✓ Фото ссылки добавлено" url={l.image_url}/>}</label><button type="button" className="danger" onClick={()=>onChange(value.filter((_:any,j:number)=>j!==i))}>Удалить ссылку</button></div>)}<button type="button" onClick={()=>onChange([...value,{title:'',description:'',image_url:'',url:''}])}>＋ Добавить отдельную ссылку</button></div>}
