'use client';
import {useMemo,useState} from 'react';
import type {Item} from '@/lib/types';
const empty={kind:'news',title:'',body:'',image_url:'',video_url:'',published_at:new Date().toISOString().slice(0,16),url:'',sort_order:0};
export default function AdminClient({initial}:{initial:Item[]}){
 const [items,setItems]=useState(initial); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<number|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const counts=useMemo(()=>({news:items.filter(x=>x.kind==='news').length,district:items.filter(x=>x.kind==='district').length,tab:items.filter(x=>x.kind==='tab').length,link:items.filter(x=>x.kind==='link').length}),[items]);
 function set(k:string,v:any){setForm((f:any)=>({...f,[k]:v}))}
 async function upload(file:File){setBusy(true);const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd});const j=await r.json();if(r.ok)set('image_url',j.url);else setMsg(j.error||'Ошибка загрузки');setBusy(false)}
 async function save(e:any){e.preventDefault();setBusy(true);setMsg('');const r=await fetch('/api/content',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...form,id:editing}:form)});const j=await r.json();if(r.ok){setItems(a=>editing?a.map(x=>x.id===editing?j:x):[j,...a]);setForm(empty);setEditing(null);setMsg('Сохранено');}else setMsg(j.error||'Ошибка');setBusy(false)}
 async function del(id:number){if(!confirm('Удалить этот элемент?'))return;const r=await fetch('/api/content',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)setItems(a=>a.filter(x=>x.id!==id));}
 function edit(x:Item){setEditing(x.id);setForm({kind:x.kind,title:x.title,body:x.body,image_url:x.image_url||'',video_url:x.video_url||'',published_at:x.published_at?new Date(x.published_at).toISOString().slice(0,16):'',url:x.url||'',sort_order:x.sort_order})}
 return <main className="admin-wrap"><header className="admin-top"><a href="/" className="brand"><img src="/avatar.jpg"/><span>Mega<span>Mine</span></span></a><div><a href="/">Сайт</a><button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}}>Выйти</button></div></header><section className="admin-head"><div><span className="eyebrow">MEGAMINE CMS</span><h1>Панель управления</h1><p>Создавай, редактируй и удаляй всё содержимое сайта.</p></div><div className="admin-stats"><b>{items.length}</b><span>элементов</span></div></section><div className="admin-grid"><section className="editor"><h2>{editing?'Редактирование':'Добавить элемент'}</h2><form onSubmit={save}><label>Тип<select value={form.kind} onChange={e=>set('kind',e.target.value)}><option value="news">Новость</option><option value="district">Район</option><option value="tab">Новая вкладка</option><option value="link">Ссылка / канал</option></select></label><label>Название<input required value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Например: Открытие нового района"/></label><label>Текст<textarea rows={6} value={form.body} onChange={e=>set('body',e.target.value)} placeholder="Описание…"/></label><div className="two"><label>Дата<input type="datetime-local" value={form.published_at} onChange={e=>set('published_at',e.target.value)}/></label><label>Порядок<input type="number" value={form.sort_order} onChange={e=>set('sort_order',e.target.value)}/></label></div><label>Фото<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><input value={form.image_url} onChange={e=>set('image_url',e.target.value)} placeholder="или вставь URL изображения"/></label><label>Видео URL<input value={form.video_url} onChange={e=>set('video_url',e.target.value)} placeholder="https://…"/></label><label>Ссылка<input value={form.url} onChange={e=>set('url',e.target.value)} placeholder="https://t.me/…"/></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?'Сохраняю…':editing?'Сохранить изменения':'Добавить'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Отмена</button>}</div>{msg&&<div className="notice">{msg}</div>}</form></section><section className="list"><div className="list-head"><h2>Контент</h2><div className="chips"><span>Новости {counts.news}</span><span>Районы {counts.district}</span><span>Вкладки {counts.tab}</span><span>Ссылки {counts.link}</span></div></div>{items.map(x=><article className="admin-item" key={x.id}>{x.image_url&&<img src={x.image_url}/>}<div className="admin-item-main"><span className="tag">{x.kind}</span><h3>{x.title}</h3><p>{x.body}</p>{x.published_at&&<small>{new Date(x.published_at).toLocaleString('ru-RU')}</small>}</div><div className="row-actions"><button onClick={()=>edit(x)}>Изменить</button><button className="danger" onClick={()=>del(x.id)}>Удалить</button></div></article>)}</section></div></main>
}
