'use client';
import {useEffect,useState} from 'react';
export default function CreateClient(){
 const [user,setUser]=useState<any>(null),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[image,setImage]=useState(''),[video,setVideo]=useState(''),[videoTitle,setVideoTitle]=useState(''),[videoDescription,setVideoDescription]=useState(''),[preview,setPreview]=useState(''),[msg,setMsg]=useState('');
 const upload=async(f:File)=>{const fd=new FormData();fd.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:fd}),j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка загрузки');return null}return j.url};
 useEffect(()=>{fetch('/api/account/me').then(r=>r.ok?r.json():null).then(x=>x&&setUser(x)).catch(()=>{})},[]);
 const signIn=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/account/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login,password})}),j=await r.json();if(!r.ok){setMsg(j.error||'Ошибка входа');return}setUser(j.user);setMsg('Вход выполнен')};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,body,image_url:image,video_url:video,video_title:videoTitle,video_description:videoDescription,video_preview:preview})}),j=await r.json().catch(()=>({}));setMsg(r.ok?'Отправлено.':'Ошибка: '+(j.error||''));if(r.ok){setTitle('');setBody('');setImage('');setVideo('');setVideoTitle('');setVideoDescription('');setPreview('')}};
 return <main className="login"><div className="login-card create-card"><span className="eyebrow">MEGAMINE BEDROCK</span><h1>Создание новости</h1>{!user?<form onSubmit={signIn}><input placeholder="Логин" value={login} onChange={e=>setLogin(e.target.value)}/><input type="password" placeholder="Пароль" value={password} onChange={e=>setPassword(e.target.value)}/><button>Войти</button></form>:<><p>Вы вошли как <b>{user.login||user.username}</b>.</p><form onSubmit={submit}><input required placeholder="Название новости" value={title} onChange={e=>setTitle(e.target.value)}/><textarea required placeholder="Текст новости" value={body} onChange={e=>setBody(e.target.value)}/><label>Изображение из устройства<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setImage(u)}}}/></label><label>Видео из устройства (отдельно)<input type="file" accept="video/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setVideo(u)}}}/></label><input placeholder="Название видео" value={videoTitle} onChange={e=>setVideoTitle(e.target.value)}/><textarea placeholder="Описание видео" value={videoDescription} onChange={e=>setVideoDescription(e.target.value)}/><label>Превью видео из устройства<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setPreview(u)}}}/></label><button>Отправить</button></form><button className="logout-btn" onClick={async()=>{await fetch('/api/account/logout',{method:'POST'});setUser(null);setMsg('Вы вышли из аккаунта')}}>Выйти из аккаунта</button></>}{msg&&<div className="notice">{msg}</div>}<a href="/">← На сайт</a></div></main>}
