'use client';
import {useEffect,useState} from 'react';
import type {Item} from '@/lib/types';
export default function CreateClient(){
 const [user,setUser]=useState<any>(null),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[image,setImage]=useState(''),[msg,setMsg]=useState(''),[mine,setMine]=useState<Item[]>([]);
 const upload=async(f:File)=>{const fd=new FormData();fd.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:fd}),j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка загрузки');return null}return j.url};
 const load=async()=>{const r=await fetch('/api/submissions',{cache:'no-store'});if(r.ok)setMine(await r.json())};
 useEffect(()=>{fetch('/api/account/me').then(r=>r.ok?r.json():null).then(x=>{if(x?.user){setUser(x.user);load()}}).catch(()=>{})},[]);
 useEffect(()=>{if(!user)return;const t=setInterval(load,3000);return()=>clearInterval(t)},[user]);
 const signIn=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/account/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login,password})}),j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Ошибка входа');return}setUser(j.user);setMsg('Вход выполнен');load()};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,body,image_url:image})}),j=await r.json().catch(()=>({}));setMsg(r.ok?(user?.is_admin?'Новость опубликована.':'Заявка отправлена администраторам.'):'Ошибка: '+(j.error||''));if(r.ok){setTitle('');setBody('');setImage('');load()}};
 return <main className="login"><div className="login-card create-card"><span className="eyebrow">MEGAMINE BEDROCK</span><h1>Создание новости</h1>{!user?<form onSubmit={signIn}><input required placeholder="Логин" value={login} onChange={e=>setLogin(e.target.value)}/><input required type="password" placeholder="Пароль" value={password} onChange={e=>setPassword(e.target.value)}/><button>Войти</button></form>:<><p>Вы вошли как <b>{user.login||user.username}</b>{user.is_creator&&!user.is_admin?' • новости отправляются на одобрение':''}.</p><form onSubmit={submit}><label>Название<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Текст новости<textarea required value={body} onChange={e=>setBody(e.target.value)}/></label><label>Изображение из устройства<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const u=await upload(f);if(u)setImage(u)}}}/></label><button>Отправить</button></form><p className="muted">Видео здесь недоступно создателям районов. Видео добавляются отдельно через меню «Видео» в админ-панели.</p><button className="logout-btn" onClick={async()=>{await fetch('/api/account/logout',{method:'POST'});setUser(null);setMine([]);setMsg('Вы вышли из аккаунта')}}>Выйти из аккаунта</button><section className="my-submissions"><h2>Мои заявки</h2>{mine.map(x=><article key={x.id}><b>{x.title}</b><span>{x.status==='pending'?'На рассмотрении':x.status==='published'?'Опубликовано':x.status==='rejected'?'Отклонено':x.status}</span></article>)}{!mine.length&&<p>Пока нет отправленных заявок.</p>}</section></>}{msg&&<div className="notice">{msg}</div>}<a href="/">← На сайт</a></div></main>}
