'use client';
import {useEffect,useState} from 'react';import type {Item} from '@/lib/types';
type Content={news:Item[];districts:Item[];tabs:Item[];links:Item[];videos:Item[]};
export default function HomeClient({content:initialContent}:{content:Content}){
 const [content,setContent]=useState(initialContent),[active,setActive]=useState('Главная'),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Item|null>(null),[linksOpen,setLinksOpen]=useState(false),[settings,setSettings]=useState<any>({app_version:'',megamine_date:'',broadcasts:[]}),[tick,setTick]=useState(Date.now());
 useEffect(()=>{const sync=async()=>{try{const [a,b]=await Promise.all([fetch('/api/content',{cache:'no-store'}),fetch('/api/settings',{cache:'no-store'})]);if(a.ok){const rows:Item[]=await a.json(),now=Date.now();setContent({news:rows.filter(x=>x.kind==='news'&&((x.status||'published')==='published'||((x.status||'')==='scheduled'&&(!x.published_at||new Date(x.published_at).getTime()<=now)))&&(!x.published_at||new Date(x.published_at).getTime()<=now)),districts:rows.filter(x=>x.kind==='district'),tabs:rows.filter(x=>x.kind==='tab'),links:rows.filter(x=>x.kind==='link'),videos:rows.filter(x=>x.kind==='video'&&((x.status||'published')==='published'||((x.status||'')==='scheduled'&&(!x.published_at||new Date(x.published_at).getTime()<=now)))&&(!x.published_at||new Date(x.published_at).getTime()<=now))})}if(b.ok)setSettings(await b.json())}catch{}};sync();const t=setInterval(sync,2500);return()=>clearInterval(t)},[]);
 useEffect(()=>{const t=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(t)},[]);
 const megaNow=clockNow(settings.megamine_date,tick); const tabs=content.tabs;
 return <div className="site-shell"><header className="topbar"><a className="brand" href="#"><img src="/avatar.jpg" alt="MegaMine"/><span>Mega<span>Mine</span></span></a><button className="mobile-menu" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'nav open':'nav'}>{['Главная','Новости','Районы','Видео',...tabs.map(t=>t.title)].map(t=><button key={t} className={active===t?'active':''} onClick={()=>{setActive(t);setMenu(false)}}>{t}</button>)}</nav></header>
 <main>{active==='Главная'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow">MINECRAFT BEDROCK • MEGAMINE UTC+4</div><h1>Добро пожаловать<br/><em>в MegaMine</em></h1><p>Живой мир, события, районы, новости и видео проекта.</p><div className="clock-card"><b>{fmtDate(megaNow)}</b><strong>{fmtTime(megaNow)}</strong><span>Дата и время MegaMine • на 1 час позже Москвы</span></div><div className="hero-actions"><button onClick={()=>setActive('Новости')}>Смотреть новости</button><button onClick={()=>setActive('Видео')}>Видео</button></div></div><div className="hero-avatar"><img src="/avatar.jpg" alt="MegaMine"/><div className="pixel-card">MEGAMINE<br/><small>ТОЛЬКО BEDROCK</small></div></div></section>{settings.broadcasts?.length>0&&<section className="broadcast-bar">{settings.broadcasts.map((b:any)=><article key={b.id}><b>📣 {b.title}</b><p>{b.body}</p></article>)}</section>}<section className="stats"><div><b>{content.news.length}</b><span>новостей</span></div><div><b>{content.districts.length}</b><span>районов</span></div><div><b>{content.videos.length}</b><span>видео</span></div><div><b>{settings.app_version||'—'}</b><span>версия сайта</span></div></section><section className="section"><div className="section-head"><div><span>01</span><h2>Последние новости</h2></div><button onClick={()=>setActive('Новости')}>Все новости →</button></div><Grid items={content.news.slice(0,3)} onOpen={setSelected} type="news"/></section><section className="section"><div className="section-head"><div><span>02</span><h2>Районы мира</h2></div><button onClick={()=>setActive('Районы')}>Все районы →</button></div><DistrictGrid items={content.districts.slice(0,4)} onOpen={setSelected}/></section></>}{active==='Новости'&&<Page title="Новости" kicker="Хроника MegaMine"><Grid items={content.news} onOpen={setSelected} type="news"/></Page>}{active==='Районы'&&<Page title="Районы" kicker="Карта мира"><DistrictGrid items={content.districts} onOpen={setSelected}/></Page>}{active==='Видео'&&<Page title="Видео" kicker="Видео MegaMine"><Grid items={content.videos} onOpen={setSelected} type="video"/></Page>}{tabs.map(t=>active===t.title&&<Page key={t.id} title={t.title} kicker="Раздел проекта"><article className="long-card">{t.image_url&&<img src={t.image_url} alt=""/>}<div><p>{t.body}</p>{Array.isArray(t.extra_links)&&t.extra_links.length>0&&<div className="modal-extra-links">{t.extra_links.map((l:any,i:number)=><a key={i} href={l.url} target="_blank" rel="noreferrer">{l.title} ↗</a>)}</div>}</div></article></Page>)}</main><footer><p>MegaMine • Только Minecraft Bedrock • {settings.app_version&&'Версия сайта '+settings.app_version}</p><div className="footer-actions"><a href="/create">Создать новость</a><button onClick={()=>setLinksOpen(true)}>Ссылки</button></div></footer>{linksOpen&&<LinksModal items={content.links} onClose={()=>setLinksOpen(false)}/>} {selected&&<InfoModal item={selected} onClose={()=>setSelected(null)}/>}</div>
}
function clockNow(dateOverride:string,tick:number){
  // Базовое время MegaMine = UTC+4. Меняемая дата не меняет часы и минуты.
  const d=new Date(tick+4*3600e3);
  if(/^\d{4}-\d{2}-\d{2}$/.test(String(dateOverride||''))){
    const [y,m,day]=String(dateOverride).split('-').map(Number);
    d.setUTCFullYear(y,m-1,day);
  }
  return d;
}
function fmtDate(d:Date){return d.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'})}function fmtTime(d:Date){return d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'UTC'})}
function Page({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <section className="page"><span className="eyebrow">{kicker}</span><h1>{title}</h1>{children}</section>}
function Grid({items,onOpen,type}:{items:Item[];onOpen:(x:Item)=>void;type:string}){if(!items.length)return <div className="empty">Пока нет материалов.</div>;return <div className="news-grid">{items.map(n=><button className="news-card card-button" key={n.id} onClick={()=>onOpen(n)}>{(n.image_url||n.video_preview)&&<img src={n.image_url||n.video_preview||''} alt=""/>}<div className="news-body"><time>{n.published_at?megaTime(n.published_at):''}</time><h3>{n.title}</h3><p>{n.body}</p><span>{type==='video'?'Смотреть видео ▶':'Подробнее →'}</span></div></button>)}</div>}
function DistrictGrid({items,onOpen}:{items:Item[];onOpen:(x:Item)=>void}){if(!items.length)return <div className="empty">Районов пока нет.</div>;return <div className="district-grid">{items.map(d=><button className="district-card card-button" key={d.id} onClick={()=>onOpen(d)}>{d.image_url&&<img src={d.image_url} alt=""/>}<div><span>РАЙОН</span><h3>{d.title}</h3><p>{d.body}</p>{d.minecraft_version&&<small>Bedrock {d.minecraft_version}</small>}</div></button>)}</div>}
function megaTime(v:string){return new Date(new Date(v).getTime()+4*3600e3).toISOString().replace('T',' ').slice(0,16)}
function InfoModal({item,onClose}:{item:Item;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><article className="info-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button>{item.image_url&&<img className="modal-image" src={item.image_url} alt=""/>}<div className="modal-content"><h2>{item.title}</h2>{item.published_at&&<time>{megaTime(item.published_at)} MegaMine</time>}<p>{item.body}</p>{Array.isArray(item.extra_links)&&item.extra_links.length>0&&<div className="modal-extra-links">{item.extra_links.map((l:any,i:number)=><a key={i} href={l.url} target="_blank" rel="noreferrer">{l.title} ↗</a>)}</div>}{item.video_url&&<div className="video-box">{item.video_preview&&<img src={item.video_preview} alt=""/>}<h3>{item.video_title||item.title}</h3>{item.video_description&&<p>{item.video_description}</p>}<video controls src={item.video_url}/></div>}</div></article></div>}
function LinksModal({items,onClose}:{items:Item[];onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><article className="info-modal links-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>Ссылки</h2><div className="links-cards">{items.map(l=><article className="link-card" key={l.id}>{l.image_url&&<img src={l.image_url} alt=""/>}<h3>{l.title}</h3><p>{l.body}</p><a href={l.url||'#'} target="_blank">Перейти ↗</a></article>)}</div></article></div>}
