import postgres from 'postgres';
const connectionString=process.env.DATABASE_URL;
export const db=connectionString?postgres(connectionString,{max:1,ssl:'require',prepare:false}):null;
export async function ensureSchema(){if(!db)return;
 await db`CREATE TABLE IF NOT EXISTS content (id BIGSERIAL PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('news','district','tab','link','video')),title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,body TEXT NOT NULL DEFAULT '',image_url TEXT,video_url TEXT,published_at TIMESTAMPTZ,url TEXT,sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS extra_links JSONB NOT NULL DEFAULT '[]'::jsonb`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'published'`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS creator_id BIGINT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS video_title TEXT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS video_description TEXT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS video_preview TEXT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS minecraft_version TEXT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS district_id BIGINT`;
 await db`ALTER TABLE content ADD COLUMN IF NOT EXISTS tab_posts JSONB NOT NULL DEFAULT '[]'::jsonb`;
 await db`CREATE INDEX IF NOT EXISTS content_district_id_idx ON content (district_id)`;
 await db`ALTER TABLE content DROP CONSTRAINT IF EXISTS content_kind_check`;
 await db`ALTER TABLE content ADD CONSTRAINT content_kind_check CHECK(kind IN ('news','district','tab','link','video'))`;
 await db`CREATE TABLE IF NOT EXISTS broadcasts (id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE TABLE IF NOT EXISTS admins (id BIGSERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name TEXT NOT NULL DEFAULT '',session_version INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 1`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'admin'`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS district_id BIGINT`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT TRUE`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS is_creator BOOLEAN NOT NULL DEFAULT FALSE`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS minecraft_nick TEXT`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS profile_description TEXT NOT NULL DEFAULT ''`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS avatar_url TEXT`;
 await db`ALTER TABLE admins ADD COLUMN IF NOT EXISTS url TEXT`;
 await db`CREATE TABLE IF NOT EXISTS creators (id BIGSERIAL PRIMARY KEY,nickname TEXT UNIQUE NOT NULL,body TEXT NOT NULL DEFAULT '',avatar_url TEXT,url TEXT,district_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE TABLE IF NOT EXISTS action_log (id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL,action TEXT NOT NULL,details TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
 await db`CREATE TABLE IF NOT EXISTS site_updates (id BIGSERIAL PRIMARY KEY,version TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',update_date DATE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
}
